### ISSUE TITLE
main.exe crash on install button pressed

### ISSUE THREAD

**Issue by brtkllo** [Angularity-Space/FractalModder#2]
on 1.2 when i click on the install button after locating the fs folder the exe file crashes, on 1.1 it freezes after pressing the install button

**Comment by aag8a** [comment]
Installing still works bad, I'll investigate it. Meanwhile, you can istall BepInEx by yourself, same with unstripped-libs. 
https://builds.bepinex.dev/projects/bepinex_be
https://hackmd.io/@ghorsington/rJuLdZTzK

**Comment by aag8a** [comment]
May I also know your PC specs?

**Comment by aag8a** [comment]
Fixed it, wait for 1.2.1
